# Generated by Django 4.2.6 on 2023-11-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='date_field',
        ),
    ]
